apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rocketmq
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rocketmq
    spec:
      containers:
      - name: broker
        image: huanwei/rocketmq:4.3.2
        command: ["sh","mqbroker", "-n","localhost:9876"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 10909
        - containerPort: 10911
        volumeMounts:
        - mountPath: /root/logs/rocketmqlogs
          name: brokerlogs
        - mountPath: /root/store
          name: brokerstore
      - name: namesrv
        image: huanwei/rocketmq:4.3.2
        command: ["sh","mqnamesrv"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9876
        volumeMounts:
        - mountPath: /root/logs/rocketmqlogs
          name: namesrvlogs
      volumes:
      - name: brokerlogs
        hostPath:
          path: /data/broker/logs
      - name: brokerstore
        hostPath:
          path: /data/broker/store
      - name: namesrvlogs
        hostPath:
          path: /data/namesrv/logs